// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SREOPSK8S/kubernetes-webhook-auth-wecom/ent/casbinrule"
	"github.com/SREOPSK8S/kubernetes-webhook-auth-wecom/ent/predicate"
)

// CasBinRuleQuery is the builder for querying CasBinRule entities.
type CasBinRuleQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.CasBinRule
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the CasBinRuleQuery builder.
func (cbrq *CasBinRuleQuery) Where(ps ...predicate.CasBinRule) *CasBinRuleQuery {
	cbrq.predicates = append(cbrq.predicates, ps...)
	return cbrq
}

// Limit adds a limit step to the query.
func (cbrq *CasBinRuleQuery) Limit(limit int) *CasBinRuleQuery {
	cbrq.limit = &limit
	return cbrq
}

// Offset adds an offset step to the query.
func (cbrq *CasBinRuleQuery) Offset(offset int) *CasBinRuleQuery {
	cbrq.offset = &offset
	return cbrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (cbrq *CasBinRuleQuery) Unique(unique bool) *CasBinRuleQuery {
	cbrq.unique = &unique
	return cbrq
}

// Order adds an order step to the query.
func (cbrq *CasBinRuleQuery) Order(o ...OrderFunc) *CasBinRuleQuery {
	cbrq.order = append(cbrq.order, o...)
	return cbrq
}

// First returns the first CasBinRule entity from the query.
// Returns a *NotFoundError when no CasBinRule was found.
func (cbrq *CasBinRuleQuery) First(ctx context.Context) (*CasBinRule, error) {
	nodes, err := cbrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{casbinrule.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) FirstX(ctx context.Context) *CasBinRule {
	node, err := cbrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first CasBinRule ID from the query.
// Returns a *NotFoundError when no CasBinRule ID was found.
func (cbrq *CasBinRuleQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cbrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{casbinrule.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) FirstIDX(ctx context.Context) int {
	id, err := cbrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single CasBinRule entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one CasBinRule entity is found.
// Returns a *NotFoundError when no CasBinRule entities are found.
func (cbrq *CasBinRuleQuery) Only(ctx context.Context) (*CasBinRule, error) {
	nodes, err := cbrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{casbinrule.Label}
	default:
		return nil, &NotSingularError{casbinrule.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) OnlyX(ctx context.Context) *CasBinRule {
	node, err := cbrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only CasBinRule ID in the query.
// Returns a *NotSingularError when more than one CasBinRule ID is found.
// Returns a *NotFoundError when no entities are found.
func (cbrq *CasBinRuleQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = cbrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = &NotSingularError{casbinrule.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) OnlyIDX(ctx context.Context) int {
	id, err := cbrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of CasBinRules.
func (cbrq *CasBinRuleQuery) All(ctx context.Context) ([]*CasBinRule, error) {
	if err := cbrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return cbrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) AllX(ctx context.Context) []*CasBinRule {
	nodes, err := cbrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of CasBinRule IDs.
func (cbrq *CasBinRuleQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := cbrq.Select(casbinrule.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) IDsX(ctx context.Context) []int {
	ids, err := cbrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (cbrq *CasBinRuleQuery) Count(ctx context.Context) (int, error) {
	if err := cbrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return cbrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) CountX(ctx context.Context) int {
	count, err := cbrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (cbrq *CasBinRuleQuery) Exist(ctx context.Context) (bool, error) {
	if err := cbrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return cbrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (cbrq *CasBinRuleQuery) ExistX(ctx context.Context) bool {
	exist, err := cbrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the CasBinRuleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (cbrq *CasBinRuleQuery) Clone() *CasBinRuleQuery {
	if cbrq == nil {
		return nil
	}
	return &CasBinRuleQuery{
		config:     cbrq.config,
		limit:      cbrq.limit,
		offset:     cbrq.offset,
		order:      append([]OrderFunc{}, cbrq.order...),
		predicates: append([]predicate.CasBinRule{}, cbrq.predicates...),
		// clone intermediate query.
		sql:    cbrq.sql.Clone(),
		path:   cbrq.path,
		unique: cbrq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Ptype string `json:"Ptype,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.CasBinRule.Query().
//		GroupBy(casbinrule.FieldPtype).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (cbrq *CasBinRuleQuery) GroupBy(field string, fields ...string) *CasBinRuleGroupBy {
	group := &CasBinRuleGroupBy{config: cbrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := cbrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return cbrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Ptype string `json:"Ptype,omitempty"`
//	}
//
//	client.CasBinRule.Query().
//		Select(casbinrule.FieldPtype).
//		Scan(ctx, &v)
//
func (cbrq *CasBinRuleQuery) Select(fields ...string) *CasBinRuleSelect {
	cbrq.fields = append(cbrq.fields, fields...)
	return &CasBinRuleSelect{CasBinRuleQuery: cbrq}
}

func (cbrq *CasBinRuleQuery) prepareQuery(ctx context.Context) error {
	for _, f := range cbrq.fields {
		if !casbinrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if cbrq.path != nil {
		prev, err := cbrq.path(ctx)
		if err != nil {
			return err
		}
		cbrq.sql = prev
	}
	return nil
}

func (cbrq *CasBinRuleQuery) sqlAll(ctx context.Context) ([]*CasBinRule, error) {
	var (
		nodes = []*CasBinRule{}
		_spec = cbrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &CasBinRule{config: cbrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, cbrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (cbrq *CasBinRuleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := cbrq.querySpec()
	_spec.Node.Columns = cbrq.fields
	if len(cbrq.fields) > 0 {
		_spec.Unique = cbrq.unique != nil && *cbrq.unique
	}
	return sqlgraph.CountNodes(ctx, cbrq.driver, _spec)
}

func (cbrq *CasBinRuleQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := cbrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (cbrq *CasBinRuleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   casbinrule.Table,
			Columns: casbinrule.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: casbinrule.FieldID,
			},
		},
		From:   cbrq.sql,
		Unique: true,
	}
	if unique := cbrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := cbrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, casbinrule.FieldID)
		for i := range fields {
			if fields[i] != casbinrule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := cbrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := cbrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := cbrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := cbrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (cbrq *CasBinRuleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(cbrq.driver.Dialect())
	t1 := builder.Table(casbinrule.Table)
	columns := cbrq.fields
	if len(columns) == 0 {
		columns = casbinrule.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if cbrq.sql != nil {
		selector = cbrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if cbrq.unique != nil && *cbrq.unique {
		selector.Distinct()
	}
	for _, p := range cbrq.predicates {
		p(selector)
	}
	for _, p := range cbrq.order {
		p(selector)
	}
	if offset := cbrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := cbrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// CasBinRuleGroupBy is the group-by builder for CasBinRule entities.
type CasBinRuleGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (cbrgb *CasBinRuleGroupBy) Aggregate(fns ...AggregateFunc) *CasBinRuleGroupBy {
	cbrgb.fns = append(cbrgb.fns, fns...)
	return cbrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (cbrgb *CasBinRuleGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := cbrgb.path(ctx)
	if err != nil {
		return err
	}
	cbrgb.sql = query
	return cbrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := cbrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(cbrgb.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := cbrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) StringsX(ctx context.Context) []string {
	v, err := cbrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cbrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) StringX(ctx context.Context) string {
	v, err := cbrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(cbrgb.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := cbrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) IntsX(ctx context.Context) []int {
	v, err := cbrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cbrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) IntX(ctx context.Context) int {
	v, err := cbrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(cbrgb.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := cbrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := cbrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cbrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) Float64X(ctx context.Context) float64 {
	v, err := cbrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(cbrgb.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := cbrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := cbrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (cbrgb *CasBinRuleGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cbrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cbrgb *CasBinRuleGroupBy) BoolX(ctx context.Context) bool {
	v, err := cbrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cbrgb *CasBinRuleGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range cbrgb.fields {
		if !casbinrule.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := cbrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cbrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (cbrgb *CasBinRuleGroupBy) sqlQuery() *sql.Selector {
	selector := cbrgb.sql.Select()
	aggregation := make([]string, 0, len(cbrgb.fns))
	for _, fn := range cbrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(cbrgb.fields)+len(cbrgb.fns))
		for _, f := range cbrgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(cbrgb.fields...)...)
}

// CasBinRuleSelect is the builder for selecting fields of CasBinRule entities.
type CasBinRuleSelect struct {
	*CasBinRuleQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (cbrs *CasBinRuleSelect) Scan(ctx context.Context, v interface{}) error {
	if err := cbrs.prepareQuery(ctx); err != nil {
		return err
	}
	cbrs.sql = cbrs.CasBinRuleQuery.sqlQuery(ctx)
	return cbrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) ScanX(ctx context.Context, v interface{}) {
	if err := cbrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Strings(ctx context.Context) ([]string, error) {
	if len(cbrs.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := cbrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) StringsX(ctx context.Context) []string {
	v, err := cbrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = cbrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) StringX(ctx context.Context) string {
	v, err := cbrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Ints(ctx context.Context) ([]int, error) {
	if len(cbrs.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := cbrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) IntsX(ctx context.Context) []int {
	v, err := cbrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = cbrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) IntX(ctx context.Context) int {
	v, err := cbrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(cbrs.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := cbrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) Float64sX(ctx context.Context) []float64 {
	v, err := cbrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = cbrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) Float64X(ctx context.Context) float64 {
	v, err := cbrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(cbrs.fields) > 1 {
		return nil, errors.New("ent: CasBinRuleSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := cbrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) BoolsX(ctx context.Context) []bool {
	v, err := cbrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (cbrs *CasBinRuleSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = cbrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{casbinrule.Label}
	default:
		err = fmt.Errorf("ent: CasBinRuleSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (cbrs *CasBinRuleSelect) BoolX(ctx context.Context) bool {
	v, err := cbrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (cbrs *CasBinRuleSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := cbrs.sql.Query()
	if err := cbrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
