// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SREOPSK8S/kubernetes-webhook-auth-wecom/ent/casbinrule"
)

// CasBinRuleCreate is the builder for creating a CasBinRule entity.
type CasBinRuleCreate struct {
	config
	mutation *CasBinRuleMutation
	hooks    []Hook
}

// SetPtype sets the "Ptype" field.
func (cbrc *CasBinRuleCreate) SetPtype(s string) *CasBinRuleCreate {
	cbrc.mutation.SetPtype(s)
	return cbrc
}

// SetNillablePtype sets the "Ptype" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillablePtype(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetPtype(*s)
	}
	return cbrc
}

// SetV0 sets the "V0" field.
func (cbrc *CasBinRuleCreate) SetV0(s string) *CasBinRuleCreate {
	cbrc.mutation.SetV0(s)
	return cbrc
}

// SetNillableV0 sets the "V0" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillableV0(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetV0(*s)
	}
	return cbrc
}

// SetV1 sets the "V1" field.
func (cbrc *CasBinRuleCreate) SetV1(s string) *CasBinRuleCreate {
	cbrc.mutation.SetV1(s)
	return cbrc
}

// SetNillableV1 sets the "V1" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillableV1(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetV1(*s)
	}
	return cbrc
}

// SetV2 sets the "V2" field.
func (cbrc *CasBinRuleCreate) SetV2(s string) *CasBinRuleCreate {
	cbrc.mutation.SetV2(s)
	return cbrc
}

// SetNillableV2 sets the "V2" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillableV2(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetV2(*s)
	}
	return cbrc
}

// SetV3 sets the "V3" field.
func (cbrc *CasBinRuleCreate) SetV3(s string) *CasBinRuleCreate {
	cbrc.mutation.SetV3(s)
	return cbrc
}

// SetNillableV3 sets the "V3" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillableV3(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetV3(*s)
	}
	return cbrc
}

// SetV4 sets the "V4" field.
func (cbrc *CasBinRuleCreate) SetV4(s string) *CasBinRuleCreate {
	cbrc.mutation.SetV4(s)
	return cbrc
}

// SetNillableV4 sets the "V4" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillableV4(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetV4(*s)
	}
	return cbrc
}

// SetV5 sets the "V5" field.
func (cbrc *CasBinRuleCreate) SetV5(s string) *CasBinRuleCreate {
	cbrc.mutation.SetV5(s)
	return cbrc
}

// SetNillableV5 sets the "V5" field if the given value is not nil.
func (cbrc *CasBinRuleCreate) SetNillableV5(s *string) *CasBinRuleCreate {
	if s != nil {
		cbrc.SetV5(*s)
	}
	return cbrc
}

// Mutation returns the CasBinRuleMutation object of the builder.
func (cbrc *CasBinRuleCreate) Mutation() *CasBinRuleMutation {
	return cbrc.mutation
}

// Save creates the CasBinRule in the database.
func (cbrc *CasBinRuleCreate) Save(ctx context.Context) (*CasBinRule, error) {
	var (
		err  error
		node *CasBinRule
	)
	cbrc.defaults()
	if len(cbrc.hooks) == 0 {
		if err = cbrc.check(); err != nil {
			return nil, err
		}
		node, err = cbrc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CasBinRuleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cbrc.check(); err != nil {
				return nil, err
			}
			cbrc.mutation = mutation
			if node, err = cbrc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(cbrc.hooks) - 1; i >= 0; i-- {
			if cbrc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cbrc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cbrc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (cbrc *CasBinRuleCreate) SaveX(ctx context.Context) *CasBinRule {
	v, err := cbrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cbrc *CasBinRuleCreate) Exec(ctx context.Context) error {
	_, err := cbrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cbrc *CasBinRuleCreate) ExecX(ctx context.Context) {
	if err := cbrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cbrc *CasBinRuleCreate) defaults() {
	if _, ok := cbrc.mutation.Ptype(); !ok {
		v := casbinrule.DefaultPtype
		cbrc.mutation.SetPtype(v)
	}
	if _, ok := cbrc.mutation.V0(); !ok {
		v := casbinrule.DefaultV0
		cbrc.mutation.SetV0(v)
	}
	if _, ok := cbrc.mutation.V1(); !ok {
		v := casbinrule.DefaultV1
		cbrc.mutation.SetV1(v)
	}
	if _, ok := cbrc.mutation.V2(); !ok {
		v := casbinrule.DefaultV2
		cbrc.mutation.SetV2(v)
	}
	if _, ok := cbrc.mutation.V3(); !ok {
		v := casbinrule.DefaultV3
		cbrc.mutation.SetV3(v)
	}
	if _, ok := cbrc.mutation.V4(); !ok {
		v := casbinrule.DefaultV4
		cbrc.mutation.SetV4(v)
	}
	if _, ok := cbrc.mutation.V5(); !ok {
		v := casbinrule.DefaultV5
		cbrc.mutation.SetV5(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cbrc *CasBinRuleCreate) check() error {
	if _, ok := cbrc.mutation.Ptype(); !ok {
		return &ValidationError{Name: "Ptype", err: errors.New(`ent: missing required field "CasBinRule.Ptype"`)}
	}
	if _, ok := cbrc.mutation.V0(); !ok {
		return &ValidationError{Name: "V0", err: errors.New(`ent: missing required field "CasBinRule.V0"`)}
	}
	if _, ok := cbrc.mutation.V1(); !ok {
		return &ValidationError{Name: "V1", err: errors.New(`ent: missing required field "CasBinRule.V1"`)}
	}
	if _, ok := cbrc.mutation.V2(); !ok {
		return &ValidationError{Name: "V2", err: errors.New(`ent: missing required field "CasBinRule.V2"`)}
	}
	if _, ok := cbrc.mutation.V3(); !ok {
		return &ValidationError{Name: "V3", err: errors.New(`ent: missing required field "CasBinRule.V3"`)}
	}
	if _, ok := cbrc.mutation.V4(); !ok {
		return &ValidationError{Name: "V4", err: errors.New(`ent: missing required field "CasBinRule.V4"`)}
	}
	if _, ok := cbrc.mutation.V5(); !ok {
		return &ValidationError{Name: "V5", err: errors.New(`ent: missing required field "CasBinRule.V5"`)}
	}
	return nil
}

func (cbrc *CasBinRuleCreate) sqlSave(ctx context.Context) (*CasBinRule, error) {
	_node, _spec := cbrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cbrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (cbrc *CasBinRuleCreate) createSpec() (*CasBinRule, *sqlgraph.CreateSpec) {
	var (
		_node = &CasBinRule{config: cbrc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: casbinrule.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: casbinrule.FieldID,
			},
		}
	)
	if value, ok := cbrc.mutation.Ptype(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldPtype,
		})
		_node.Ptype = value
	}
	if value, ok := cbrc.mutation.V0(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldV0,
		})
		_node.V0 = value
	}
	if value, ok := cbrc.mutation.V1(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldV1,
		})
		_node.V1 = value
	}
	if value, ok := cbrc.mutation.V2(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldV2,
		})
		_node.V2 = value
	}
	if value, ok := cbrc.mutation.V3(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldV3,
		})
		_node.V3 = value
	}
	if value, ok := cbrc.mutation.V4(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldV4,
		})
		_node.V4 = value
	}
	if value, ok := cbrc.mutation.V5(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: casbinrule.FieldV5,
		})
		_node.V5 = value
	}
	return _node, _spec
}

// CasBinRuleCreateBulk is the builder for creating many CasBinRule entities in bulk.
type CasBinRuleCreateBulk struct {
	config
	builders []*CasBinRuleCreate
}

// Save creates the CasBinRule entities in the database.
func (cbrcb *CasBinRuleCreateBulk) Save(ctx context.Context) ([]*CasBinRule, error) {
	specs := make([]*sqlgraph.CreateSpec, len(cbrcb.builders))
	nodes := make([]*CasBinRule, len(cbrcb.builders))
	mutators := make([]Mutator, len(cbrcb.builders))
	for i := range cbrcb.builders {
		func(i int, root context.Context) {
			builder := cbrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CasBinRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cbrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cbrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cbrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cbrcb *CasBinRuleCreateBulk) SaveX(ctx context.Context) []*CasBinRule {
	v, err := cbrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cbrcb *CasBinRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := cbrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cbrcb *CasBinRuleCreateBulk) ExecX(ctx context.Context) {
	if err := cbrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
