// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/SREOPSK8S/kubernetes-webhook-auth-wecom/ent/casbinrule"
)

// CasBinRule is the model entity for the CasBinRule schema.
type CasBinRule struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Ptype holds the value of the "Ptype" field.
	Ptype string `json:"Ptype,omitempty"`
	// V0 holds the value of the "V0" field.
	V0 string `json:"V0,omitempty"`
	// V1 holds the value of the "V1" field.
	V1 string `json:"V1,omitempty"`
	// V2 holds the value of the "V2" field.
	V2 string `json:"V2,omitempty"`
	// V3 holds the value of the "V3" field.
	V3 string `json:"V3,omitempty"`
	// V4 holds the value of the "V4" field.
	V4 string `json:"V4,omitempty"`
	// V5 holds the value of the "V5" field.
	V5 string `json:"V5,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CasBinRule) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case casbinrule.FieldID:
			values[i] = new(sql.NullInt64)
		case casbinrule.FieldPtype, casbinrule.FieldV0, casbinrule.FieldV1, casbinrule.FieldV2, casbinrule.FieldV3, casbinrule.FieldV4, casbinrule.FieldV5:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type CasBinRule", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CasBinRule fields.
func (cbr *CasBinRule) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case casbinrule.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cbr.ID = int(value.Int64)
		case casbinrule.FieldPtype:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field Ptype", values[i])
			} else if value.Valid {
				cbr.Ptype = value.String
			}
		case casbinrule.FieldV0:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V0", values[i])
			} else if value.Valid {
				cbr.V0 = value.String
			}
		case casbinrule.FieldV1:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V1", values[i])
			} else if value.Valid {
				cbr.V1 = value.String
			}
		case casbinrule.FieldV2:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V2", values[i])
			} else if value.Valid {
				cbr.V2 = value.String
			}
		case casbinrule.FieldV3:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V3", values[i])
			} else if value.Valid {
				cbr.V3 = value.String
			}
		case casbinrule.FieldV4:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V4", values[i])
			} else if value.Valid {
				cbr.V4 = value.String
			}
		case casbinrule.FieldV5:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field V5", values[i])
			} else if value.Valid {
				cbr.V5 = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this CasBinRule.
// Note that you need to call CasBinRule.Unwrap() before calling this method if this CasBinRule
// was returned from a transaction, and the transaction was committed or rolled back.
func (cbr *CasBinRule) Update() *CasBinRuleUpdateOne {
	return (&CasBinRuleClient{config: cbr.config}).UpdateOne(cbr)
}

// Unwrap unwraps the CasBinRule entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cbr *CasBinRule) Unwrap() *CasBinRule {
	tx, ok := cbr.config.driver.(*txDriver)
	if !ok {
		panic("ent: CasBinRule is not a transactional entity")
	}
	cbr.config.driver = tx.drv
	return cbr
}

// String implements the fmt.Stringer.
func (cbr *CasBinRule) String() string {
	var builder strings.Builder
	builder.WriteString("CasBinRule(")
	builder.WriteString(fmt.Sprintf("id=%v", cbr.ID))
	builder.WriteString(", Ptype=")
	builder.WriteString(cbr.Ptype)
	builder.WriteString(", V0=")
	builder.WriteString(cbr.V0)
	builder.WriteString(", V1=")
	builder.WriteString(cbr.V1)
	builder.WriteString(", V2=")
	builder.WriteString(cbr.V2)
	builder.WriteString(", V3=")
	builder.WriteString(cbr.V3)
	builder.WriteString(", V4=")
	builder.WriteString(cbr.V4)
	builder.WriteString(", V5=")
	builder.WriteString(cbr.V5)
	builder.WriteByte(')')
	return builder.String()
}

// CasBinRules is a parsable slice of CasBinRule.
type CasBinRules []*CasBinRule

func (cbr CasBinRules) config(cfg config) {
	for _i := range cbr {
		cbr[_i].config = cfg
	}
}
