// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/SREOPSK8S/kubernetes-webhook-auth-wecom/ent/casbinrule"
	"github.com/SREOPSK8S/kubernetes-webhook-auth-wecom/ent/predicate"
)

// CasBinRuleDelete is the builder for deleting a CasBinRule entity.
type CasBinRuleDelete struct {
	config
	hooks    []Hook
	mutation *CasBinRuleMutation
}

// Where appends a list predicates to the CasBinRuleDelete builder.
func (cbrd *CasBinRuleDelete) Where(ps ...predicate.CasBinRule) *CasBinRuleDelete {
	cbrd.mutation.Where(ps...)
	return cbrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cbrd *CasBinRuleDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cbrd.hooks) == 0 {
		affected, err = cbrd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CasBinRuleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cbrd.mutation = mutation
			affected, err = cbrd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cbrd.hooks) - 1; i >= 0; i-- {
			if cbrd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cbrd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cbrd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cbrd *CasBinRuleDelete) ExecX(ctx context.Context) int {
	n, err := cbrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cbrd *CasBinRuleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: casbinrule.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: casbinrule.FieldID,
			},
		},
	}
	if ps := cbrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, cbrd.driver, _spec)
}

// CasBinRuleDeleteOne is the builder for deleting a single CasBinRule entity.
type CasBinRuleDeleteOne struct {
	cbrd *CasBinRuleDelete
}

// Exec executes the deletion query.
func (cbrdo *CasBinRuleDeleteOne) Exec(ctx context.Context) error {
	n, err := cbrdo.cbrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{casbinrule.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cbrdo *CasBinRuleDeleteOne) ExecX(ctx context.Context) {
	cbrdo.cbrd.ExecX(ctx)
}
