// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Audit is the predicate function for audit builders.
type Audit func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)
